Updation in resume functionaliy.
null-open-security-community/null-jobs-backend-2.0 pull request #60
Opened 2024-01-22 16:06 UTC by Parth858

Instead of remove documents I have modified the code for replacing the old media files with new one so that we don't need to first remove documents and then add new media file we can directly replace it with previous one.

2024-01-22 18:13 UTC, hims1911 approved these changes
@Himan10 merge this lgtm

2024-01-23 18:39 UTC, Himan10 requested changes

2024-01-23 18:39 UTC, Himan10 commented on apps/jobs/views.py
> +        if document_type == values.RESUME_DOCUMENT_TYPE:
where are the changes for these constants ?

2024-01-25 20:46 UTC, hims1911 approved these changes

2024-01-25 20:47 UTC, Himan10 approved these changes

2024-01-25 20:48 UTC, merged